# Generated by Django 4.0.2 on 2022-04-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_loginform'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='empt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('dpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.dpt')),
            ],
            options={
                'db_table': 'empt',
            },
        ),
    ]
