# Generated by Django 4.0.2 on 2022-04-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_registrationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrationform',
        ),
    ]
