# Generated by Django 4.0.2 on 2022-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_registrationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrationform',
        ),
    ]
