# Generated by Django 4.0.2 on 2022-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0011_registrationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('Area', models.CharField(max_length=30)),
                ('floors', models.CharField(max_length=30)),
            ],
        ),
    ]
