# Generated by Django 4.0.2 on 2022-05-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0012_homeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('Area', models.CharField(max_length=30)),
                ('floors', models.CharField(max_length=30)),
            ],
        ),
    ]
