# Generated by Django 4.0.2 on 2022-05-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0014_car1form'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.TextField()),
                ('ans', models.TextField()),
            ],
            options={
                'db_table': 'faq',
            },
        ),
    ]
