# Generated by Django 4.0.2 on 2022-05-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0016_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
